apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teamspeak3.fullname" . }}
  labels:
    {{- include "teamspeak3.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "teamspeak3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
    {{- toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "teamspeak3.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: teamspeak-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (include "teamspeak3.fullname" .) "data") | quote  }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ts-voice
              containerPort: 9987
              protocol: UDP
            - name: ts-filetransfer
              containerPort: 30033
              protocol: TCP
            - name: ts-serverquery
              containerPort: 10022
              protocol: TCP
            - name: ts-http-query
              containerPort: 10080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TS3SERVER_LICENSE
              value: accept
            - name: TS3SERVER_QUERY_PROTOCOLS
              value: "{{ .Values.queryProtocols }}"
          volumeMounts:
            - mountPath: /var/ts3server/
              name: teamspeak-data
        - name: {{ .Chart.Name }}-teamspeak3-server-viewer
          image: "{{ .Values.ts3ServerViewer.image.repository }}:{{ .Values.ts3ServerViewer.image.tag }}"
          imagePullPolicy: {{ .Values.ts3ServerViewer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TS_API_KEY
              value: "{{ .Values.ts3ServerViewer.tsApiKey }}"
            - name: TS_API_URL
              value: "{{ .Values.ts3ServerViewer.tsApiUrl}}"
            
          
        
