{{- $fullName := include "teamspeak3.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "teamspeak3.fullname" . }}
  labels:
    {{- include "teamspeak3.labels" . | nindent 4 }}
  {{- with .Values.ts3ServerViewer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ts3ServerViewer.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ts3ServerViewer.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ts3ServerViewer.ingress.tls }}
  tls:
{{ toYaml .Values.ts3ServerViewer.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.ts3ServerViewer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $fullName }}-web
                port: 
                  name: http
  {{- end }}
