{{- $fullName := include "teamspeak3.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-web
  labels:
    {{- include "teamspeak3.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    {{- include "teamspeak3.selectorLabels" . | nindent 4 }} 
